// Mocks generated by Mockito 5.4.4 from annotations
// in flux_notes/test/editor_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flux_notes/data/models/note_model.dart' as _i3;
import 'package:flux_notes/data/repositories/note_repository.dart' as _i4;
import 'package:isar/isar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIsar_0 extends _i1.SmartFake implements _i2.Isar {
  _FakeIsar_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNote_1 extends _i1.SmartFake implements _i3.Note {
  _FakeNote_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i4.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Isar> get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _i5.Future<_i2.Isar>.value(_FakeIsar_0(
          this,
          Invocation.getter(#db),
        )),
      ) as _i5.Future<_i2.Isar>);

  @override
  set db(_i5.Future<_i2.Isar>? _db) => super.noSuchMethod(
        Invocation.setter(
          #db,
          _db,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.Isar> openDB() => (super.noSuchMethod(
        Invocation.method(
          #openDB,
          [],
        ),
        returnValue: _i5.Future<_i2.Isar>.value(_FakeIsar_0(
          this,
          Invocation.method(
            #openDB,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Isar>);

  @override
  _i5.Future<_i3.Note> createNote() => (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [],
        ),
        returnValue: _i5.Future<_i3.Note>.value(_FakeNote_1(
          this,
          Invocation.method(
            #createNote,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Note>);

  @override
  _i5.Future<void> saveNote(_i3.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #saveNote,
          [note],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Note?> getNote(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNote,
          [id],
        ),
        returnValue: _i5.Future<_i3.Note?>.value(),
      ) as _i5.Future<_i3.Note?>);

  @override
  _i5.Stream<List<_i3.Note>> getAllNotes() => (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [],
        ),
        returnValue: _i5.Stream<List<_i3.Note>>.empty(),
      ) as _i5.Stream<List<_i3.Note>>);

  @override
  _i5.Future<void> deleteNote(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> checkAndSeedDemoNote() => (super.noSuchMethod(
        Invocation.method(
          #checkAndSeedDemoNote,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllNotes() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllNotes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveNotes(List<_i3.Note>? notes) => (super.noSuchMethod(
        Invocation.method(
          #saveNotes,
          [notes],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Note>> getAllNotesList() => (super.noSuchMethod(
        Invocation.method(
          #getAllNotesList,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Note>>.value(<_i3.Note>[]),
      ) as _i5.Future<List<_i3.Note>>);
}
